import { popularCountries } from "@/lib/countries";
import { plansForCountry, formatData, formatPrice } from "@/lib/plans";

export default function AdminPlansPage() {
  return (
    <div className="space-y-6">
      <p className="text-sm text-white/55">
        Catalog preview — prices are generated by the deterministic engine in{" "}
        <code className="rounded bg-white/10 px-1.5 py-0.5 font-mono text-xs">lib/plans.ts</code>{" "}
        until the supplier rate sheet is connected. Showing popular destinations.
      </p>
      {popularCountries.slice(0, 6).map((country) => (
        <div key={country.code} className="glass overflow-x-auto rounded-2xl">
          <h2 className="px-5 pt-5 font-semibold">
            {country.flag} {country.name}
          </h2>
          <table className="mt-3 w-full min-w-[32rem] text-left text-sm">
            <thead className="border-b border-white/10 text-xs uppercase tracking-wide text-white/40">
              <tr>
                <th className="px-5 py-3">Plan</th>
                <th className="px-5 py-3">Data</th>
                <th className="px-5 py-3">Validity</th>
                <th className="px-5 py-3">Price</th>
                <th className="px-5 py-3">Per GB</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-white/5">
              {plansForCountry(country).map((p) => (
                <tr key={p.id}>
                  <td className="px-5 py-3">{p.label}</td>
                  <td className="px-5 py-3">{formatData(p.dataGb)}</td>
                  <td className="px-5 py-3 text-white/60">{p.days} days</td>
                  <td className="px-5 py-3">{formatPrice(p.priceUsd)}</td>
                  <td className="px-5 py-3 text-white/50">
                    {typeof p.dataGb === "number"
                      ? formatPrice(p.priceUsd / p.dataGb)
                      : "—"}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      ))}
    </div>
  );
}
